name: Check Push
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run affected:lint
    - run: npm run affected:test
    - run: npm run affected:e2e
